parser: babel-eslint

env:
  browser: true

globals:
  ENV: readonly
  GOOGLE_CLIENT_ID: readonly

extends:
  - eslint:recommended
  - airbnb-base
  - prettier

plugins:
  - prettier
  - compat

rules:
  prettier/prettier: error
  compat/compat: error
  no-console: warn
  class-methods-use-this: off
  no-param-reassign: off
  no-use-before-define:
    - error
    - functions: false
